### ISSUE TITLE
[JOIN] 자바스크립트 사용하는 프론트엔드 개발자 입니다!

### ISSUE THREAD

**Issue by rjsdnql123** [Road-of-CODEr/stupid-week#42]
// 이메일을 적어주시면 초대장을 드리겠습니다.

- email: '' 취업전 같이 공부하고 싶습니다! rjsdnql12@gmail.com

**Comment by 1ilsang** [comment]
안녕하세요. 해당 주소가 존재하지 않거나 휴면 상태라고 나오는데 확인해 주시겠어요?

**Comment by rjsdnql123** [comment]
잘못입력 했네요,,, rjsdnql123@gmail.com 입니다@

**Comment by 1ilsang** [comment]
발송완료
