### ISSUE TITLE
[JOIN] 스터디 참여하고 싶어요!

### ISSUE THREAD

**Issue by sunivers** [Road-of-CODEr/stupid-week#63]
벌써부터 지키지 못할 제가 두렵지만 일단 질러봅니다!

- email: 'soyoungp02@gmail.com'

**Comment by 1ilsang** [comment]
안녕하세요! 참여 감사합니다. [기여 가이드라인](https://github.com/Road-of-CODEr/stupid-week/blob/master/.github/CONTRIBUTING.md)을 확인해 주시고 PR 날려주세요.

어려움 있으시면 언제든 알려주세요.
